bash clickhouse_processing/01_create_dimensions_table.sh
bash clickhouse_processing/02_lead_counts.sh
bash clickhouse_processing/03_unqualified_lead_counts.sh
bash clickhouse_processing/04_new_lead_counts.sh
bash clickhouse_processing/05_buyer_counts.sh
bash clickhouse_processing/06_new_buyer_counts.sh
bash clickhouse_processing/07_new_buyer_income.sh

bash clickhouse_processing/09_create_reports_table.sh
